### ISSUE TITLE
cat_view.html

### ISSUE THREAD

**Issue by ChrisT-CC** [C-Undritz/Jan22-Hackathon-Team12#13]
# Create a "**cat view**" template
1. Inherit the navbar and footer from the base.html template
2. Display a cat **image**
3. Display a cat **name**
4. Display a cat **description**
5. Add a button to choose this cat
6. Add a button to go to the next cat (unless we use carusel)

_We could skip the choose_cat template and turn this into a carusel_

**Comment by C-Undritz** [comment]
I have done 1 - 4 in terms of grabbing the information from the DB.  However it needs styling.  The page is pet_profile.html
